language: go

go:
  - 1.8

services:
  - docker

before_script:
  - go get -v github.com/bblfsh/sdk/...
  - bblfsh-sdk prepare-build .
  - go get -v -t ./...

script:
  - make test integration-test

after_success:
  - make push
